### ISSUE TITLE
Failed to run test case

### ISSUE THREAD

**Issue by ryao-mdanderson** [RTH-tools/crisprroots#1]
Dear author,

I followed README testcase command, it runs but hits an error at fastq stage. May you please provide some suggestions what could be the issue?

 (crisprroots-1.2) [ryao@r1prpsciapp13 QPRT_DEL268T_chr16_10M-40M]$ snakemake -s /home/ryao/crisprroots/CRISPRroots-1.2/run.smk --use-conda --cores 1
Building DAG of jobs...
...
Activating conda environment: .snakemake/conda/0ce42c9c632e258b34e7c943b1639106_
[Tue Apr 25 22:41:01 2023]
Error in rule FASTQC_qualitycheck_after_cleaning:
    jobid: 67
    input: /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M/QPRT_DEL268T_1_chr16_10M-40M.fastq.gz
    output: /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1-1_fastqc_after_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M
    log: /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/logs/preproc/1-1_fastqc_after_cutadapt_cleaning.QPRT_DEL268T_1_chr16_10M-40M.log (check log file(s) for error details)
    conda-env: /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/.snakemake/conda/0ce42c9c632e258b34e7c943b1639106_
    shell:
        

        [ ! -d "/rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1-1_fastqc_after_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M" ] && mkdir /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1-1_fastqc_after_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M

        #******PARAMETERS*****
        # -t : number of threads to be used
	    # -o: path to output directory

        fastqc -t 1 /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M/QPRT_DEL268T_1_chr16_10M-40M.fastq.gz -o /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1-1_fastqc_after_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M &>/rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/logs/preproc/1-1_fastqc_after_cutadapt_cleaning.QPRT_DEL268T_1_chr16_10M-40M.log
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job FASTQC_qualitycheck_after_cleaning since they might be corrupted:
/rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/preproc/1-1_fastqc_after_cutadapt_cleaning/QPRT_DEL268T_1_chr16_10M-40M
Shutting down, this might take some time.

Thanks,
Rong Yao

**Comment by gcorsi** [comment]
Dear Rong,
Thank you for bringing this to our attention!

I was able to recreate the error, which in my log file is described as follows:
`java: symbol lookup error: java: undefined symbol: JLI_StringDup`

Is this the same error you have in your log file? You can find the log file at:
`/rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/results/logs/preproc/1-1_fastqc_after_cutadapt_cleaning.QPRT_DEL268T_1_chr16_10M-40M.log`

Assuming this is the error, this is due to a conflict between conda packages (which may have changed since our last test). I'm making a new definition of the conda pre-processing environment to solve this problem and will get back to you shortly. 

Best,
Giulia

**Comment by ryao-mdanderson** [comment]
Dear Giulia:

Thank you for replying me.
I looked at my log file, it has the same error message as yours.

Thanks for fixing this!
Rong

**Comment by gcorsi** [comment]
Hi Rong,

it seems this problem affects the conda installation only on some platforms. Sorry we did not catch this case during testing. 
None of the conda environments I attempted fixed the problem on the failing platform. 

The following is a workaround to fix the conda environment after it is created. It's not a clean solution, but it works.

1. enter the folder in which you have been executing snakemake. It should be this one:
`cd /rsrch3/home/itops/ryao/crisprroots/CRISPRroots_test_dataset/QPRT_DEL268T_chr16_10M-40M/`

2. activate the problematic conda environment
 `conda activate .snakemake/conda/0ce42c9c632e258b34e7c943b1639106_`

3. reinstall java-jdk in the conda environment. Say "Yes" when asked by conda if you want to proceed.
`conda install --force-reinstall java-jdk`

4. exit the conda environment
`conda deactivate`

5. touch the yaml file that snakemake creates to keep track of the conda files.
`touch .snakemake/conda/0ce42c9c632e258b34e7c943b1639106_.yaml`

6. now, you can run again the pipeline
`snakemake -s /home/ryao/crisprroots/CRISPRroots-1.2/run.smk --use-conda --cores 1`

This worked for me, and I did not get any other error. 

A downside of this fix is that when you will run the pipeline on your data, in another folder, you will have to repeat this procedure again for the new conda environment that will be created for that project. You will find the path to the conda environment in the output, after the first run fails. In the text you posted it was the line "Activating conda environment: .snakemake/conda/0ce42c9c632e258b34e7c943b1639106_".

I'm working on a Dockerfile as alternative to Conda. It will be more stable and will not require installations. 

Best,
Giulia

**Comment by ryao-mdanderson** [comment]
Hello Giulia:

Thank you very much for your reply! I am sorry I did not response to your reply earlier, I did not receive an email notification for the post and dropped the ball down. My bad.

I look forward to a container version of the application to be using on our HPC cluster.

Thanks again!
Rong

**Comment by ryao-mdanderson** [comment]
Hello Giulia:

I want to update with you. Your suggestion for the conda work around works. 
We also look forward to a container version :)

Thank you!
Rong

**Comment by ryao-mdanderson** [comment]
Hello Giulia:

I am following up for an ETA of a container version if possible.

Thank you!
Rong

**Comment by gcorsi** [comment]
Hi Rong,

thank you for following up, I am glad to hear that the work around could temporarily fix the issue. 
I have made a first version of a docker, it can be downloaded from Docker Hub:
`docker pull gcorsi1993/crisprroots`
In addition to the tools required to run CRISPRroots, within the docker you'll find the CRISPRroots code (v1.2) and the test folder. I could run CRISPRroots on the test data on a standard AWS EC2 without error. I plan to do some tests on a larger dataset this weekend (June 24-25). I expect to give an update by the end of next week.

Best,
Giulia

**Comment by ryao-mdanderson** [comment]
Hi Giulia,

Thank you very much for your efforts to provide us a docker version. I will test it. Please take your time to work on larger dataset. This is not urgent for us, since your work around is just fine.

Best,
Rong

**Comment by ryao-mdanderson** [comment]
Hi Giulia,

We use singularity instead of docker on HPC cluster, I am able to pull your container. I have a question of using, here is what I tried so far:

I use singularity version 3.7.0.
$ singularity pull docker://gcorsi1993/crisprroots
  -- generate crisprroots_latest.sif 
$ singularity run crisprroots_latest.sif 
 Singularity>  which snakemake
 /usr/local/bin/snakemake
 Singularity> cd /usr/
 Singularity> ls
 bin  games  include  lib  local  sbin  share  src
 Singularity> cd src/
 Singularity> ls -l 
 total 17124
drwxr-s---  8 root root      319 Nov 16  2021 CRISPRroots-1.2
drwxr-s---  4 root root      100 Dec  6  2021 CRISPRroots_test_dataset
drwxr-x---  4 root root       78 Jun 16  2021 RIsearch-1.2
drwxr-xr-x 13 root root      620 Jun  5 09:25 ViennaRNA-2.5.1
drwxrwxrwx  8 root root     3222 Jun  5 20:52 bbmap
drwxr-xr-x 19 root root      399 Jun  5 20:58 conda
drwxr-xr-x  4 root root      321 Feb 19  2021 gatk-4.2.0.0
-rw-r--r--  1 root root 17532035 Dec  6  2021 picard.jar
drwxr-xr-x  7 root root      135 Jun  5 21:01 subread-2.0.1-source
Singularity> ls -l CRISPRroots-1.2/
ls: cannot open directory 'CRISPRroots-1.2/': Permission denied
 
I am not clear if the permission prevents me to access the source / test. If you have a command how to run container, it will be helpful.

Thank you!
Rong

**Comment by gcorsi** [comment]
Hi Rong,

Have you tried running Singularity as sudo? When I pull the Docker and run it, I can access the folder and change its permissions.

Ideally, the CRISPRroots code folder and test data shouldn't be part of the Docker image, as they were only for testing purposes.

To run CRISPRroots with Singularity, we should run Snakemake directly with the "--use-singularity" option. However, I'm facing difficulties binding the data folders to Singularity due to my limited experience with it. I had to modify the original code of CRISPRroots to make it run with Singularity using Snakemake, so unfortunately you cannot try this option with the code available online yet.

Apologies for the delay in my response. Since I changed job, it's been challenging to keep up with notifications for previous projects.

**Comment by ryao-mdanderson** [comment]
Dear Giulia,

 Thank you for responding to my message. It has been very kind of you to provide work around and solutions etc. Our cluster user has been using the conda work around.

 Good luck with your new position.

Rong

**Comment by gcorsi** [comment]
Dear Rong,

It was a pleasure for me to help! I have found a good recipe for making Singularity work. I am adding some features to the software, particularly to make the output easier to interpret. I expect version 1.3 to be released in late August or September.

Thank you again for using our software. If you have any further questions, including those regarding the output, please do not hesitate to contact us.

Best wishes with your projects!

Giulia
